export function getTechIconClass(tech: string): string | null {
  const map: Record<string, string> = {
    '.net': 'devicon-dotnetcore-plain',
    '.net 8': 'devicon-dotnetcore-plain',
    '.net 10': 'devicon-dotnetcore-plain',
    'c#': 'devicon-csharp-plain',
    'asp.net core': 'devicon-dotnetcore-plain',
    'entity framework core': 'devicon-dotnetcore-plain',
    'ef core': 'devicon-dotnetcore-plain',
    'nuget': 'devicon-nuget-original',
    'azure devops': 'devicon-azure-plain',
    'signalr': 'devicon-dotnetcore-plain',
    'react': 'devicon-react-original',
    'react 18': 'devicon-react-original',
    'react 19': 'devicon-react-original',
    'typescript': 'devicon-typescript-plain',
    'javascript': 'devicon-javascript-plain',
    'javascript es6+': 'devicon-javascript-plain',
    'javascript es2020+': 'devicon-javascript-plain',
    'html5': 'devicon-html5-plain',
    'css3': 'devicon-css3-plain',
    'tailwind css': 'devicon-tailwindcss-plain',
    'tailwind css v4': 'devicon-tailwindcss-plain',
    'tailwindcss': 'devicon-tailwindcss-plain',
    'vite': 'devicon-vitejs-plain',
    'bootstrap 5': 'devicon-bootstrap-plain',
    'python': 'devicon-python-plain',
    'postgresql': 'devicon-postgresql-plain',
    'mongodb': 'devicon-mongodb-plain',
    'sqlite': 'devicon-sqlite-plain',
    'docker': 'devicon-docker-plain',
    'kubernetes': 'devicon-kubernetes-plain',
    'helm': 'devicon-helm-plain',
    'openai': 'devicon-openai-plain',
    'google sheets api': 'devicon-google-plain',
    'recharts': 'devicon-react-original',
    'tanstack start': 'devicon-react-original',
    'excalidraw': 'devicon-javascript-plain',
  };
  return map[tech.toLowerCase().trim()] ?? null;
}
